### ISSUE TITLE
google.api_core.exceptions.InvalidArgument: 400 Failed to find a valid credential. The request to create a transfer config is supposed to contain an authorization code.

### ISSUE THREAD

**Issue by Rstar1998** [googleapis/python-bigquery-datatransfer#433]
Library version : 3.10
Platform : Google cloud shell and user had all permissions and even clicked on authorize pop up by google cloud
Code snippet :
```
transfer_config = transfer_client.create_transfer_config(
            bigquery_datatransfer.CreateTransferConfigRequest(
                parent=parent,
                transfer_config=transfer_config,

            )

```

Error Description :
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.9/dist-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Failed to find a valid credential. The request to create a transfer config is supposed to contain an authorization code."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:142.250.4.95:443 {grpc_message:"Failed to find a valid credential. The request to create a transfer config is supposed to contain an authorization code.", grpc_status:3, created_time:"2023-02-01T05:14:19.286168048+00:00"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sid/data-pipelines/GCP/big_lake_architecture/automation/create_pipelines_new_gen_with_choice_mysql.py", line 266, in <module>
    transfer_config = transfer_client.create_transfer_config(
  File "/home/sid/.local/lib/python3.9/site-packages/google/cloud/bigquery_datatransfer_v1/services/data_transfer_service/client.py", line 803, in create_transfer_config
    response = rpc(
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/gapic_v1/method.py", line 113, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InvalidArgument: 400 Failed to find a valid credential. The request to create a transfer config is supposed to contain an authorization code.
```

**Comment by parthea** [comment]
Hello @Rstar1998 , 

After looking through some internal bugs, I found a few possible solutions

1) There is authentication is required by the BigQuery DataTransfer service when using it the first time. If it's the first time that you're scheduling a query, please try to run a dummy BigQuery Data Transfer manually via the Google Cloud Console before trying to schedule the query via the python client. (Googlers see b/175342736).

2) Please ensure that the location in the `transfer_config` matches the location of the dataset specified. (b/257506729).

Please let me know if you still encounter the issue.

**Comment by parthea** [comment]
Closing as a response was provided in https://github.com/googleapis/python-bigquery-datatransfer/issues/433#issuecomment-1431717669
